development: &dev
  adapter: postgresql
  encoding: unicode
  database: equalise_development
  pool: 20
  username: postgres
  password:

test: &test
  <<: *dev
  database: equalise_test

production:
  <<: *dev
  adapter: postgresql
  encoding: unicode
  database: equalise_production
  pool:5
  username:jylee93
  password: 1234

cucumber:
  <<: *test
